export const categoriesMap = {
  "TOP GAMES": [
    "TOP GAMES",
    "Andar Bahar",
    "Indian Games",
    "Roulette",
    "Baccarat",
    "Dragon Tiger",
    "Blackjack",
    "32 Cards",
    "Poker",
    "DICE GAMES",
    "GAME SHOW",
    "Lottery",
    "Virtual Casino",
    "Virtual Sports",
    "Tv Games",
    "Casual Games",
    "Rummy",
    "Crash Games",
    "Slot games",

    // "Arcade Games",
    // "Bingo",
    // "Dealer",
    // "Fish Shooting",
    // "Games",
    // "LIVE",
    // "Lobby",
    // "Mini Games",
    // "SLOT",
    // "Scratch Cards",
    // "Sports",
    // "TABLE",
  ],
  Ezugi: [
    "TOP GAMES",
    "Andar Bahar",
    "32 Cards",
    "Baccarat",
    "Blackjack",
    "DICE GAMES",
    "Indian Games",
    "Poker",
    "Roulette",
  ],
  "Evolution Gaming": [
    "TOP GAMES",
    "Baccarat",
    "Blackjack",
    "Casual Games",
    "DICE GAMES",
    "Dealer",
    "Dragon Tiger",
    "GAME SHOW",
    "Games",
    "Indian Games",
    "Lobby",
    "Lottery",
    "Poker",
    "Roulette",
    "Crash Games",
    "Slot games",
  ],
  "Super Spade Games": [
    "TOP GAMES",
    "Baccarat",
    "Dragon Tiger",
    "Indian Games",
    "Roulette",
  ],
  SuperNowa: [
    "TOP GAMES",
    "Andar Bahar",
    "Baccarat",
    "Dragon Tiger",
    "Indian Games",
    "Poker",
    "Roulette",
    "Virtual Casino",
  ],
  "Bombay Live": [
    "TOP GAMES",
    "Baccarat",
    "Blackjack",
    "Dragon Tiger",
    "Games",
    "Indian Games",
    "Roulette",
  ],
  "Asia Gaming": [
    "TOP GAMES",
    "Baccarat",
    "Casual Games",
    "DICE GAMES",
    "Dragon Tiger",
    "Roulette",
  ],
  SPRIBE: ["TOP GAMES", "Casual Games", "Lottery", "Crash Games"],
  Playtech: [
    "TOP GAMES",
    "Andar Bahar",
    "Baccarat",
    "Blackjack",
    "Casual Games",
    "DICE GAMES",
    "Dragon Tiger",
    "GAME SHOW",
    "Poker",
    "Roulette",
    "Slot games",
  ],
  "Pragmatic Play Live": [
    "TOP GAMES",
    "Baccarat",
    "Blackjack",
    "DICE GAMES",
    "Dealer",
    "Draon Tiger",
    "GAME SHOW",
    "Lobby",
    "Roulette",
  ],
  "Beter Live": [
    "TOP GAMES",
    "Andar Bahar",
    "Baccarat",
    "Blackjack",
    "DICE GAMES",
    "Poker",
    "Roulette",
  ],
  TVBet: [
    "TOP GAMES",
    "Andar Bahar",
    "Blackjack",
    "Dealer",
    "Indian Games",
    "Lottery",
    "Poker",
    "Roulette",
  ],
  VivoGaming: [
    "TOP GAMES",
    "Andar Bahar",
    "Baccarat",
    "Blackjack",
    "Dragon Tiger",
    "Indian Games",
    "Poker",
    "Roulette",
  ],
  "Royal Gaming": [
    "TOP GAMES",
    "Andar Bahar",
    "Baccarat",
    "DICE GAMES",
    "Dealer",
    "Dragon Tiger",
    "Indian Games",
    "Roulette",
    "TABLE",
  ],
  Bgaming: [
    "TOP GAMES",
    "Blackjack",
    "Casual Games",
    "DICE GAMES",
    "Scratch Cards",
    "Crash Games",
    "Slot games",
  ],

  // DRGS: ["Arcade Games", "Fish Shooting"],
  // RICH88: ["Arcade Games", "Bingo"],
  // "Oryx Gaming": ["Arcade Games"],
  // OneTouch: ["Baccarat"],
  // Winfinity: ["Baccarat", "Blackjack", "Dealer", "Dragon Tiger", "Roulette"],
  // Betsoft: ["Baccarat", "Blackjack"],
  // Tangente: ["Baccarat", "Blackjack", "Dealer", "Poker", "Roulette"],
  // Habanero: ["Baccarat"],
  // "Hacksaw Gaming": ["Baccarat", "Dealer", "Lottery", "Scratch Cards"],

  // "Play'n Go": [
  //   "Bingo",
  //   "Blackjack",
  //   "Dealer",
  //   "GAME SHOW",
  //   "Poker",
  //   "Roulette",
  // ],
  // "Caleta Gaming": ["Bingo"],
  // Genii: ["Blackjack"],
  // Wazdan: ["Blackjack", "DICE GAMES", "Poker", "Roulette"],
  // "Relax Gaming": ["Blackjack", "Roulette"],
  // "Pragmatic Play 2": ["Casual Games", "Virtual Sports"],
  // "Macaw Gaming": ["Casual Games"],
  // "Smartsoft Gaming": ["Casual Games", "Lottery", "Roulette"],
  // "JiLi Gaming": [
  //   "DICE GAMES",
  //   "Dealer",
  //   "Fish Shooting",
  //   "Indian Games",
  //   "Lottery",
  //   "Poker",
  //   "Virtual Casino",
  // ],
  // "Pragmatic Play": ["Dealer"],
  // SEXYBCRT: ["LIVE"],
  // HORSEBOOK: ["LIVE"],
  // "Lotto Instant Win": ["Lottery"],
  // "Yuvi Games": ["Mini Games"],
  // "Yuvi Games Lobby": ["Mini Games"],
  // "Evoplay Entertainment": ["Poker", "Roulette", "Scratch Cards"],
  // CandleBets: ["Roulette"],
  // RT: ["SLOT", "TABLE"],
  // BGaming: ["Scratch Cards"],
  // SportsBook: ["Sports"],
  // Exchange: ["Sports"],
  // Premium: ["Sports"],
  // Virtuals: ["Sports"],
  // KINGMAKER: ["TABLE"],
  // "BetGames.TV": ["Tv Games"],
  // BetGames: ["Tv Games"],
  // "Royal Gaming Virtual": ["Virtual Casino"],
  // "Golden Race": ["Virtual Sports"],
  // Parlaybay: ["Virtual Sports"],
};
